export default function Header() {
  return (
    <>
      <link
        rel="stylesheet"
        href="https://cache.ltn.com.tw/css/rwd_head_tail.css?20230808"
      />
      <link
        rel="stylesheet"
        href="https://cache.ltn.com.tw/css/rwd_head_cover.css?20230323"
      />
      <div className="ltnheader boxTitle boxText" data-desc="置頂選單">
        <div className="Hcon">
          <div className="logo">
            <a
              title="自由時報"
              href="https://www.ltn.com.tw"
              data-desc="自由時報"
              className="logo_B"
            >
              <img
                src="https://cache.ltn.com.tw/images/rwd_ltnlogo.png"
                alt="自由時報"
                title="自由時報"
              />
            </a>
            <a
              title="自由時報"
              href="https://www.ltn.com.tw"
              data-desc="自由時報"
              className="logo_S"
            >
              <img
                src="https://cache.ltn.com.tw/images/logo_foot.png"
                alt="自由時報"
                title="自由時報"
              />
            </a>
          </div>
          {/* Header 選單 */}
          <div className="useMobi">
            <ul>
              <li>
                <a
                  title="即時"
                  href="https://news.ltn.com.tw/list/breakingnews"
                  data-desc="即時"
                >
                  即時
                </a>
              </li>
              <li>
                <a
                  title="熱門"
                  href="https://news.ltn.com.tw/list/breakingnews/popular"
                  data-desc="熱門"
                >
                  熱門
                </a>
              </li>
              <li>
                <a
                  title="政治"
                  href="https://news.ltn.com.tw/list/breakingnews/politics"
                  data-desc="政治"
                >
                  政治
                </a>
              </li>
              <li>
                <img
                  className="newChannel"
                  src="https://cache.ltn.com.tw/images/new.gif"
                  alt="newChannel"
                  title="newChannel"
                />
                <a title="軍武" href="https://def.ltn.com.tw" data-desc="軍武">
                  軍武
                </a>
              </li>
              <li>
                <a
                  title="社會"
                  href="https://news.ltn.com.tw/list/breakingnews/society"
                  data-desc="社會"
                >
                  社會
                </a>
              </li>
              <li>
                <a
                  title="生活"
                  href="https://news.ltn.com.tw/list/breakingnews/life"
                  data-desc="生活"
                >
                  生活
                </a>
              </li>
              <li>
                <a
                  title="健康"
                  href="https://health.ltn.com.tw"
                  data-desc="健康"
                >
                  健康
                </a>
              </li>
              <li>
                <a
                  title="國際"
                  href="https://news.ltn.com.tw/list/breakingnews/world"
                  data-desc="國際"
                >
                  國際
                </a>
              </li>
              <li>
                <a
                  title="地方"
                  href="https://news.ltn.com.tw/list/breakingnews/local"
                  data-desc="地方"
                >
                  地方
                </a>
              </li>
              <li>
                <a
                  title="蒐奇"
                  href="https://news.ltn.com.tw/list/breakingnews/novelty"
                  data-desc="蒐奇"
                >
                  蒐奇
                </a>
              </li>
              <li>
                <a
                  title="影音"
                  href="https://video.ltn.com.tw"
                  data-desc="影音"
                >
                  影音
                </a>
              </li>
              <li>
                <a title="財經" href="https://ec.ltn.com.tw" data-desc="財經">
                  財經
                </a>
              </li>
              <li>
                <a title="娛樂" href="https://ent.ltn.com.tw" data-desc="娛樂">
                  娛樂
                </a>
              </li>
              <li>
                <a title="汽車" href="https://auto.ltn.com.tw" data-desc="汽車">
                  汽車
                </a>
              </li>
              <li>
                <a
                  title="時尚"
                  href="https://istyle.ltn.com.tw"
                  data-desc="時尚"
                >
                  時尚
                </a>
              </li>
              <li>
                <a
                  title="體育"
                  href="https://sports.ltn.com.tw"
                  data-desc="體育"
                >
                  體育
                </a>
              </li>
              <li>
                <a title="3C" href="https://3c.ltn.com.tw" data-desc="3C">
                  3 C
                </a>
              </li>
              <li>
                <a title="評論" href="https://talk.ltn.com.tw" data-desc="評論">
                  評論
                </a>
              </li>
              <li>
                <a title="藝文" href="https://art.ltn.com.tw" data-desc="藝文">
                  藝文
                </a>
              </li>
              <li>
                <a
                  title="玩咖"
                  href="https://playing.ltn.com.tw/"
                  data-desc="玩咖"
                >
                  玩咖
                </a>
              </li>
              <li>
                <a title="食譜" href="https://food.ltn.com.tw" data-desc="食譜">
                  食譜
                </a>
              </li>
              <li>
                <a
                  title="地產"
                  href="https://estate.ltn.com.tw"
                  data-desc="地產"
                >
                  地產
                </a>
              </li>
              <li className="li_project">
                <a
                  title="專區"
                  href="https://features.ltn.com.tw/"
                  data-desc="專區"
                >
                  專區
                </a>
              </li>
              <li className="li_TT">
                <a
                  title="TAIPEI TIMES"
                  href="http://www.taipeitimes.com/"
                  data-desc="TAIPEI TIMES"
                  target="_blank"
                >
                  TAIPEI TIMES
                </a>
              </li>
              <li>
                <a
                  title="求職"
                  href="https://ltn_jobs.yes123.com.tw/index.asp"
                  data-desc="求職"
                  target="_blank"
                >
                  求職
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
